management:
  context-path: /manage
  security:
    roles: SUPER_ADMIN

server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 600 # 10 minutes

spring:
  application:
    name: bicentennial
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC