security:
  ignored: /h2-console/**

server:
  port: 13003

spring:
  datasource:
    platform: h2
  h2.console.enabled: true
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false