/* Order of columns are ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION, EMAIL, NAME, PHONE_NUMBER, INFO, ADDRESS_LINE, CLUSTER, COUNTRY, LATITUDE, LONGTITUDE*/
INSERT INTO EVENT_T VALUES();
